INSTALL_TARGET_PROCESSES = @@PROJECTNAME@@

include @@THEOS@@/makefiles/common.mk

APPLICATION_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = main.m @@CLASSPREFIX@@AppDelegate.m @@CLASSPREFIX@@RootViewController.m
@@PROJECTNAME@@_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
