include @@THEOS@@/makefiles/common.mk

FRAMEWORK_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = @@PROJECTNAME@@.mm
@@PROJECTNAME@@_INSTALL_PATH = /Library/Frameworks

include $(THEOS_MAKE_PATH)/framework.mk
