include @@THEOS@@/makefiles/common.mk

TWEAK_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_OBJC_FILES = @@PROJECTNAME@@.m
@@PROJECTNAME@@_FRAMEWORKS = Foundation UIKit
@@PROJECTNAME@@_LIBRARIES = activator

include $(THEOS_MAKE_PATH)/tweak.mk
