TARGET := iphone:clang:latest:7.0

include @@THEOS@@/makefiles/common.mk

TOOL_NAME = @@PROJECTNAME@@

@@PROJECTNAME@@_FILES = main.m
@@PROJECTNAME@@_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tool.mk
