THEOS_LEAN_AND_MEAN = 1
@@KILL_RULE@@
include @@THEOS@@/makefiles/common.mk

TWEAK_NAME = @@PROJECTNAME@@

@@PROJECTNAME@@_FILES = Event.x
@@PROJECTNAME@@_LIBRARIES = activator
@@PROJECTNAME@@_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
