TARGET = iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = @@PROJECTNAME@@

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = @@PROJECTNAME@@

@@PROJECTNAME@@_FILES = ContentView.swift @@PROJECTNAME@@App.swift

include $(THEOS_MAKE_PATH)/application.mk
