include @@THEOS@@/makefiles/common.mk

BUNDLE_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = @@PROJECTNAME@@ViewController.m
@@PROJECTNAME@@_INSTALL_PATH = /Library/WeeLoader/Plugins
@@PROJECTNAME@@_FRAMEWORKS = UIKit CoreGraphics
@@PROJECTNAME@@_PRIVATE_FRAMEWORKS = SpringBoardUIServices
@@KILL_PROCS@@
include $(THEOS_MAKE_PATH)/bundle.mk
