@@KILL_RULE@@
include @@THEOS@@/makefiles/common.mk

BUNDLE_NAME = @@PROJECTNAME@@

@@PROJECTNAME@@_FILES = @@PROJECTNAME@@ViewController.m
@@PROJECTNAME@@_FRAMEWORKS = UIKit CoreGraphics
@@PROJECTNAME@@_PRIVATE_FRAMEWORKS = SpringBoardUIServices
@@PROJECTNAME@@_INSTALL_PATH = /Library/WeeLoader/Plugins

include $(THEOS_MAKE_PATH)/bundle.mk
