include @@THEOS@@/makefiles/common.mk

BUNDLE_NAME = @@PROJECTNAME@@LockScreen
@@PROJECTNAME@@LockScreen_FILES = @@PROJECTNAME@@.mm
@@PROJECTNAME@@LockScreen_FRAMEWORKS = UIKit
@@PROJECTNAME@@LockScreen_PRIVATE_FRAMEWORKS = SpringBoardUI
@@PROJECTNAME@@LockScreen_INSTALL_PATH = /System/Library/SpringBoardPlugins/
@@KILL_PROCS@@
include $(THEOS_MAKE_PATH)/bundle.mk
