THEOS_LEAN_AND_MEAN = 1
@@KILL_RULE@@
include @@THEOS@@/makefiles/common.mk

TWEAK_NAME = @@PROJECTNAME@@

@@PROJECTNAME@@_FILES = Listener.x
@@PROJECTNAME@@_LIBRARIES = activator

include $(THEOS_MAKE_PATH)/tweak.mk
